### ISSUE TITLE
a question about selectVmOnHost method in BasicEdgeOrchestrator

### ISSUE THREAD

**Issue by xiaoxiaopingzi** [CagataySonmez/EdgeCloudSim#1]
In the selectVmOnHost (Task task) method of BasicEdgeOrchestrator.java,
When the policy is "RANDOM_FIT", if there is no loop, a random targetVmCapacity may be less than requiredCapacity, which will result in the selectedVM is null, do not need a loop here?

**Comment by CagataySonmez** [comment]
In this basic Edge Orchestrator, RANDOM_FIT does not guarantee that the selected VM provides enough capacity for the given task. So, you are right; selectedVM can be null. In this case, related task would be logged as rejected in submitTaskToEdgeDevice function in MobileDeviceManager.java.

If you think RANDOM_FIT should provide a sufficient VM, you can modify this part by randomly picking the VMs which have enough capacity, or simply adding a loop.
