### ISSUE TITLE
help about latency

### ISSUE THREAD

**Issue by amrouchk** [CagataySonmez/EdgeCloudSim#15]
Dear Edgecloudsim team
I would like to thank you for providing such very useful tool
I have question about network delay
in CLI of the simulation results it shows three values:  average network delay:  (LAN delay, MAN delay, WAN delay) which one is considered the cloud or edge delay
is there any way to calculate the delay for both cloud/edge together??
Regards

**Comment by CagataySonmez** [comment]
Hello,

EdgeCloudSim records LAN, MAN and WAN delay in SimLogger.java:

_public void setUploadDelay(int taskId, double delay, NETWORK_DELAY_TYPES delayType)_
_public void setDownloadDelay(int taskId, double delay, NETWORK_DELAY_TYPES delayType)_

You can set related values in your _MobileDeviceManager_ implementation, for example:

_SimLogger.getInstance().setDownloadDelay(task.getCloudletId(), delay, NETWORK_DELAY_TYPES.WLAN_DELAY);_

**LAN** delay provided in the simulation result refers to the communication delay between mobile device and the edge server.
**MAN** delay refers to the communication delay among edge servers.
**WAN** delay refers to the communication delay between mobile device and the edge server.
**Average** network delay refers to the average value of all delay types.

If you just want to consider LAN and WAN delay (without MAN delay), you can modify SimLogger.Java.
In line 304, you can see the following code block:

_networkDelay[value.getTaskType()] += value.getNetworkDelay();_

value.getNetworkDelay() provides the sum of all communication delays, you can modify this part as follows:

_networkDelay[value.getTaskType()] += value.getNetworkDelay(NETWORK_DELAY_TYPES.WLAN_DELAY);_ 
_networkDelay[value.getTaskType()] += value.getNetworkDelay(NETWORK_DELAY_TYPES.WAN_DELAY);_

Another simpler way to avoid MAN delay is discarding all setUploadDelay and setDownloadDelay function calls with NETWORK_DELAY_TYPES.MAN_DELAY argument in your MobileDeviceManager.

Did my comments answer your question properly?

Regards,
Cagatay

**Comment by amrouchk** [comment]
Dear Cagatay,
Thanks so much for the reply,

-First: I am still a bit confused about this : 
> Wan delay refers to the communication delay between mobile device and the edge server. 
did you want to say it is the delay between mobile device and cloud server ?
 if no cloud-mobile delay is provided how can I compare two different scenarios with edge enabled and without edge? 
-Second: am I able to calculate the latency which is the round-trip time of a packet likewise delay which is time between two network entities?
appreciate your answer in advance.
regards

**Comment by CagataySonmez** [comment]
Dear Amrouchk,

Sorry it was my mistake, 'edge server' should have been 'cloud server'; I edited my previous comment.

Actually I couldn't understand your second question properly.
Do you want to get latency or RTT?
These terms can mean different things, according to my experience, I can summarize them as follows
**latency**: the time consumed to transfer the packets from A to B
**RTT**: the time consumed to transfer the packets from A to B + the processing time + the time consumed to transfer the packets from B to A

The network delay used in edgecloudsim is end-to-end delay between devices such as the edge server, cloud server and mobile devices.
The network delay includes bot the upload and download delay.
If you want to report the upload and download delay separately, you should modify SimLogger.java file according to your needs.
When it comes to the service time, it is similar to RTT.

By the way, in the sample applications the network delay is calculated via simple M/M/1 queue model and experiment based values.
If you need more sophisticated model, you should implement your own network model by extending NetworkModel class.

Regards,
Cagatay

**Comment by CagataySonmez** [comment]
Dear Amrouchk,

I think the average service time, which is provided in the simulation results, is what you are looking for.
You can also plot average service time graph by using below matlab function:
scripts/sample_app1/matlab/plotAvgProcessingTime.m

I can explain the upload and download delay as follows:
Each task has an input and output data.
The input data is sent (uploaded) to the target server.
After the task is completed, the result (output data) is downloaded.
The delay value is the time consumed for the upload and download operations.

Regards,
Cagatay

**Comment by amrouchk** [comment]
Dear Cagatay,
Thanks so much for the help. since everything is clear now, I will close this request. 
Best Regards.
