### ISSUE TITLE
There is a bug in the file CONTRIBUTING.md

### ISSUE THREAD

**Issue by Derfei** [CagataySonmez/EdgeCloudSim#18]
Step 2: Specify a new remote upstream repository:
![image](https://user-images.githubusercontent.com/19963815/53155851-e87a4700-35f8-11e9-9809-de52f1354d43.png)
redundancy of `git remote add upstream`

**Comment by CagataySonmez** [comment]
Your pull request #20 already solves this problem.
Thanks for contributing!
