### ISSUE TITLE
Visual tool for displaying the network topology

### ISSUE THREAD

**Issue by emersonbarea** [CagataySonmez/EdgeCloudSim#3]
Hi. How I use a visual tool for displaying the network topology that is mentioned in README.md?
Thank you.

**Comment by CagataySonmez** [comment]
Hi emersonbarea,

Actually visual tool is listed in the Needed Features section and it is not implemented yet.
We are waiting for the contributors who are willing to implement these features.

Thanks for your interest,
Cagatay
