### ISSUE TITLE
Installation tutorial

### ISSUE THREAD

**Issue by alexander989** [CagataySonmez/EdgeCloudSim#4]
HI 
Could you plz add a tutorial of the complete installation.

**Comment by Dhwani2011** [comment]
Kindly provide tutorials stepwise regarding installation of Edge Cloud Sim

**Comment by shashankshampi** [comment]
I too have same problem ....not able to run this project.
Please provide step wise detail to execute your sample work

**Comment by CagataySonmez** [comment]
Dear All,

We have added two wiki pages to explain running sample application on both Eclipse and Linux terminal.
Please see them in the below links:

[EdgeCloudSim in Eclipse: step by step installation & running sample application](https://github.com/CagataySonmez/EdgeCloudSim/wiki/EdgeCloudSim-in-Eclipse:-step-by-step-installation-&-running-sample-application)
[Running sample application on the Linux terminal](https://github.com/CagataySonmez/EdgeCloudSim/wiki/Running-sample-application-on-the-Linux-terminal)

We will also plan to prepare a tutorial video in the future.

Thanks for your kind recommendation,
Cagatya
