### ISSUE TITLE
Could anyone provide an explanation of the meaning of the parameters？

### ISSUE THREAD

**Issue by wangxinqun** [CagataySonmez/EdgeCloudSim#46]
There are three files named 'applications.xml', 'edge_devices.xml','default_config.properties'. 
I have difficulties in understanding the meanings of the parameters in them. 
Could anyone give me guidance? I would appreciate it！

**Comment by kwangalt** [comment]
Those three files are configuration (settings) files where you can make your own design of the system by changing the values for the parameters in them. You can even create new parameters and assign your own values depending on the nature of your problem.

'applications.xml' - settings about the applications architecture (number of applications and the properties of each). Here you find parameters like application name (eg. AUGMENTED_REALITY), delay sensitivity, task length, etc all of which are properties of an application.

'edge_devices.xml' - settings about the edge network architecture (number of datacenters and the properties of each). Here you find parameters like hosts, virtual machines, processor speed, memory etc.

'default_config.properties' - settings about the cloud and mobile devices architecture. Also the general simulation parameters like simulation time, number of mobile devices, orchestrator policy, simulation scenario, etc. Most of these simulation parameters' values are supposed to be matched with those in the matlab files to ensure consistent results.  

You can open the SimSettings.java file and follow through to see how the configuration parameters above are read and used in the program. Also in case you create your own new parameters, you will have to update the same java file with your new parameters. 

I hope that helps.

**Comment by wangxinqun** [comment]
Thank you!
That really helps me a lot!😀
