### ISSUE TITLE
How to run your project ???

### ISSUE THREAD

**Issue by shashankshampi** [CagataySonmez/EdgeCloudSim#6]
Please give a complete command to run your sample project.
I tried running main file in  eclipse and got error.
Then i tried running in terminal but still got error. Please write the complete command to run.
![screenshot from 2018-03-19 19-57-23](https://user-images.githubusercontent.com/20582834/37601368-daf9be84-2baf-11e8-8b1a-c427a9003594.png)
![screenshot from 2018-03-19 19-57-05](https://user-images.githubusercontent.com/20582834/37601369-db40fea2-2baf-11e8-9a5e-27af5f48a825.png)

**Comment by CagataySonmez** [comment]
Dear Shashank,

There was a minor issue on the default config file paths in mainApp.java.
We have resolved it with d105a0e5742af3b3a9eae0a84efcdf17b73661c2.
Could you please check below wiki pages to run sample application?

[EdgeCloudSim in Eclipse: step by step installation & running sample application](https://github.com/CagataySonmez/EdgeCloudSim/wiki/EdgeCloudSim-in-Eclipse:-step-by-step-installation-&-running-sample-application)
[Running sample application on the Linux terminal](https://github.com/CagataySonmez/EdgeCloudSim/wiki/Running-sample-application-on-the-Linux-terminal)

Thanks for your interest,
Cagatay

**Comment by shashankshampi** [comment]
Thank you for your so fast response. Working fine now....Great work
